# Querying Data

Import Libraries and setting parameters

In [1]:
import sys
import os

sys.path.insert(0, os.path.abspath('C:/Users/dagic/OneDrive/Documents/KAIM/Week_2/fintech-review-analytics'))

print('Path set. Python will now look in:', os.path.abspath('C:/Users/dagic/OneDrive/Documents/KAIM/Week_2/fintech-review-analytics'))

Path set. Python will now look in: C:\Users\dagic\OneDrive\Documents\KAIM\Week_2\fintech-review-analytics

In [2]:
import psycopg2
import pandas as pd

from src.db_helper import run_query

In [3]:
conn = psycopg2.connect(
    host="localhost",
    database="bank_reviews",
    user="admin_user",
    password="654123"
)

In [5]:
sql = "SELECT * FROM banks limit 10;"

run_query(sql, conn)

C:\Users\dagic\OneDrive\Documents\KAIM\Week_2\fintech-review-analytics\src\db_helper.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,bank_id,bank_name,app_name,bank_code
0,4,Commercial Bank of Ethiopia,CBE Mobile Banking,CBE
1,5,Bank of Abyssinia,BoA Mobile,Bank of Abyssinia
2,6,Dashen Bank,Dashen Bank Super App,Dashen Bank

In [4]:
sql = "SELECT * FROM reviews limit 10;"

run_query(sql, conn)

C:\Users\dagic\OneDrive\Documents\KAIM\Week_2\fintech-review-analytics\src\db_helper.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,review_id,bank_id,review_text,rating,review_date,sentiment_label,sentiment_score,identified_theme,source
0,1,6,best app so far. thank you,5,2026-05-15,positive,0.999848,Other,Google Play
1,2,6,Very Annoying App i tried to open virtual bank...,1,2026-05-14,negative,-0.999444,Account,Google Play
2,3,6,good,5,2026-05-14,positive,0.999816,Other,Google Play
3,4,6,good,5,2026-05-14,positive,0.999816,Other,Google Play
4,5,6,good app but it was doesnt work other bank tra...,5,2026-05-14,positive,-0.996920,UX,Google Play
5,6,6,good,5,2026-05-14,positive,0.999816,Other,Google Play
6,7,6,"i swear to god , By using this app, I won a Sa...",5,2026-05-14,positive,0.999208,Other,Google Play
7,8,6,good and easier to used,5,2026-05-14,positive,0.999848,Other,Google Play
8,9,6,bad mobile banking at all,1,2026-05-13,negative,-0.999807,Other,Google Play
9,10,6,very nice app.,5,2026-05-13,positive,0.999862,Other,Google Play

## Average rating per restaurant

In [8]:
# Average rating per banks

sql = """
SELECT r.bank_name, ROUND(AVG(v.rating), 2) AS avg_rating
FROM reviews v
JOIN banks r ON r.bank_id = v.bank_id
GROUP BY r.bank_name;
"""

run_query(sql, conn)

C:\Users\dagic\OneDrive\Documents\KAIM\Week_2\fintech-review-analytics\src\db_helper.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

                     bank_name  avg_rating
0  Commercial Bank of Ethiopia        4.08
1                  Dashen Bank        3.92
2            Bank of Abyssinia        3.55